version: '3'

services:
  postgres:
    image: postgis/postgis
    shm_size: 2g
    ports:
      - 5432:5432
    networks:
      - postgres
      - api
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      PGDATA: ${PGDATA}
    volumes:
      - $PWD/raw_data:/var/lib/postgresql/data/raw_data
    healthcheck:
      test: [ "CMD", "pg_isready", "-U", "postgres" ]
      interval: 5s
      retries: 5
    restart: always

  api:
    container_name: api
    build: ./
    ports:
      - "8001:8000"
    networks:
      - api
    environment:
      POSTGRES_HOST: postgres
      POSTGRES_PORT: ${POSTGRES_PORT}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      ENGINE_TYPE: ${ENGINE_TYPE}
      SLACK_WEBHOOK_URL: ${SLACK_WEBHOOK_URL}
    command: bash -c "python3 -m uvicorn app.main:app --host 0.0.0.0"
    depends_on:
      - postgres

networks:
  postgres:
    driver: bridge
  api:
    driver: bridge
